### ISSUE TITLE
Input images of higher resolution.

### ISSUE THREAD

**Issue by waleedrazakhan92** [andrewhou1/GeomConsistentFR#10]
Hello, first of all thank you for such a great work. I've used it for 256x256 resolution and it  works great. But my use-case is for images of resolution 1024x1024. I would like to know what needs to be changed in the code to make it work with the 1024x1024 resolution for both the relighting single image and the light transfer code.

**Comment by andrewhou1** [comment]
Thanks for your interest in our work! So as the model is intended for 256x256, the best way to apply it to 1024x1024 is to downsample your image first to 256x256 and pass it to the network. The output will be 256x256, which you can upsample to 1024x1024. Hope that helps!

**Comment by waleedrazakhan92** [comment]
@andrewhou1 Thankyou for a quick reply. So I understand from your comment there's no way this pretrained model can be applied to images of higher resolution i.e 1024x1024. If i were to retrain the entire model from scratch, would you please direct me on what changes do i need to make in code and data to make the training work for 1024x1024 resolution.

**Comment by andrewhou1** [comment]
Sure, to be completely honest I think it could be challenging since we use many existing methods to estimate the intrinsic component supervision, such as the depth and albedo supervision. SfSNet estimates the albedo at 128x128, which we resize to 256x256. I think if we were to resize the existing supervision to 1024x1024, there would be problems with the poor supervision anyway due to the significant upsampling. This would of course affect the trained model as well, which is why I stuck with 256x256. 

That's why I mentioned that resizing your 1024x1024 image first to 256x256 is likely the easiest and best solution. Then, once you get the output, simply resize back to 1024x1024.

**Comment by waleedrazakhan92** [comment]
Again thankyou for a quick reply. I'll look for other possible solutions for my problem.
