### ISSUE TITLE
Inconsistent shadows.

### ISSUE THREAD

**Issue by waleedrazakhan92** [andrewhou1/GeomConsistentFR#14]
Hello, I'm trying to generate a variety of shadows from different angles using the x,y and z direction coordinates. However some times the shadows that are generated are not very smooth and consistent and even seams start to appear. Or sometimes aliasing start to appear in the results. I'm attaching some of the images for reference. Please let me know if there is a setting or something either in the preprocessing or postprocessing that can be done to improve the results.

![4](https://user-images.githubusercontent.com/10988422/222105837-204f0c3e-a54a-4463-abad-67b8e04eed39.png)
![3](https://user-images.githubusercontent.com/10988422/222105853-a8ef823d-1df0-4f19-a429-8a2efe115cde.png)
![2](https://user-images.githubusercontent.com/10988422/222105859-fb4d3600-7eb1-48d3-8ced-3100b0318919.png)

I've also noticed that the generated shadow masks aren't exactly smooth themselves and is there a reason behind it? or something that can be improved upon?
![download (1) (1)](https://user-images.githubusercontent.com/10988422/222106976-75ffaf30-5d7d-40d4-8445-b557b685044f.png)
P.S the mask is not of the same image above.

**Comment by andrewhou1** [comment]
Hi, so that may happen if the estimated shape is not perfect, specifically that the shadow may not be smooth. If the shape is inaccurate, shadows could appear where they shouldn't. However, to deal with the seams, you can raise the number of sampled points from 160 to something higher. Specifically this variable: 

self.num_sample_points = 160
