### ISSUE TITLE
Depth output very bad

### ISSUE THREAD

**Issue by wzds2015** [andrewhou1/GeomConsistentFR#7]

**Comment by andrewhou1** [comment]
Hi were you able to resolve this issue? Since our network is trained for 256x256 resolution, it is best to first match this resolution before trying to feed your image to our model. You can try cropping the image first using our provided cropping code: recrop_CelebA-HQ_images.py which crops the image to 256x256 using face detection. Another way is you can crop out a square portion of the image and resize it to 256x256 and feed it to our model. Let me know if you need any more assistance!
